// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_gTM1lxJHpMz5vEl73amjmKtygFQUd8g',
    appId: '1:460105482088:web:4fb9a2d3ca5a9c4991a0dd',
    messagingSenderId: '460105482088',
    projectId: 'bonusgame-52eb6',
    authDomain: 'bonusgame-52eb6.firebaseapp.com',
    databaseURL: 'https://bonusgame-52eb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bonusgame-52eb6.firebasestorage.app',
    measurementId: 'G-0NSB066RDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZuTntqrq68-2NifozmT755uFkP9RFMdo',
    appId: '1:460105482088:android:ba7246fd0932d07591a0dd',
    messagingSenderId: '460105482088',
    projectId: 'bonusgame-52eb6',
    databaseURL: 'https://bonusgame-52eb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bonusgame-52eb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc3t1QjSS4uzBgwRyZW-Ywr_Iu-HoLIx0',
    appId: '1:460105482088:ios:26dcd4134e12374f91a0dd',
    messagingSenderId: '460105482088',
    projectId: 'bonusgame-52eb6',
    databaseURL: 'https://bonusgame-52eb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bonusgame-52eb6.firebasestorage.app',
    iosBundleId: 'com.example.bonus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc3t1QjSS4uzBgwRyZW-Ywr_Iu-HoLIx0',
    appId: '1:460105482088:ios:26dcd4134e12374f91a0dd',
    messagingSenderId: '460105482088',
    projectId: 'bonusgame-52eb6',
    databaseURL: 'https://bonusgame-52eb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bonusgame-52eb6.firebasestorage.app',
    iosBundleId: 'com.example.bonus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_gTM1lxJHpMz5vEl73amjmKtygFQUd8g',
    appId: '1:460105482088:web:ba9cb57620c4f37491a0dd',
    messagingSenderId: '460105482088',
    projectId: 'bonusgame-52eb6',
    authDomain: 'bonusgame-52eb6.firebaseapp.com',
    databaseURL: 'https://bonusgame-52eb6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'bonusgame-52eb6.firebasestorage.app',
    measurementId: 'G-WYE9M8G4DC',
  );
}
