class Strings {
  static const String langEn = 'en';
  static const String langHe = 'he';

  static const Map<String, Map<String, String>> _localized = {
    langEn: {
      // General
      'ok': 'OK',
      'close': 'Close',
      'cancel': 'Cancel',
      'continue': 'Continue',
      'create': 'Create',
      'join': 'Join',
      'player1': 'Player 1',
      'player2': 'Player 2',
      'yourName': 'Your Name',
      'enterYourName': 'Enter Your Name',
      'waitingForPlayer': 'Waiting for player to join...',
      'roomCreated': 'Room Created!',
      'roomPin': 'Your room PIN is: {pin}\n\nShare it with a friend to play.',
      'joinRoom': 'Join Room',
      'createRoom': 'Create Room',
      'onlineGame': 'Online Game',
      'localGame': 'Local Game',
      'playVsComputer': 'Play vs Computer',
      'instructions': 'Instructions',
      'startGame': 'Start Game',
      'gameOver': 'Game Over',
      'winner': '{winner} wins!',
      'itsATie': "It's a tie!",
      'computer': 'Computer',
      'computerHand': "Computer's Hand",
      'yourHand': 'Your Hand',
      'turn': 'Turn',
      'score': 'Score',
      'time': 'Time: ',
      'replaceLetter': 'Replace Letter',
      'selectLetterToReplace': 'Select a letter to replace',
      'costPoints': 'Cost: {cost} points ({count}{ordinal} replacement)',
      'yourScore': 'Your score: {score}',
      'letterReplaced': 'Letter replaced! -{cost} points',
      'needPointsToReplace': 'You need at least {cost} points to replace a letter!',
      'chooseLetterForJoker': 'Choose Letter for Joker',
      'bonusCollected': 'Bonus Collected!',
      'invalidWordsFound': 'Invalid Words Found',
      'invalidWordsDesc': 'The following words are not in the dictionary:',
      'acceptWordsOrSkip': 'Would you like to accept these words anyway, or skip your turn?',
      'skipTurn': 'Skip Turn',
      'acceptWords': 'Accept Words',
      'totalPoints': 'Total Points:',
      'extraTurnGained': 'Extra Turn Gained!',
      'invalid': 'Invalid',
      'accepted': 'Accepted',
      'wordsCreated': 'Words Created:',
      'synchronizing': 'Synchronizing game state...',
      'playerLeft': 'Player Left',
      'playerLeftDesc': 'The other player has left the game.',
      'turnSkipped': 'Turn Skipped',
      'turnSkippedDesc': 'You did nothing and your turn was passed.',
      'invalidMove': 'Invalid Move',
      'roomNotFound': 'Room not found!',
      'enterValidPin': 'Please enter a valid 6-digit PIN.',
      'instructionsTitle': 'Instructions',
      'deck': 'Deck: ',
      'points': 'points',
      'endTurn': 'End Turn',
      'handOf': "{name}'s Hand",
      // Add more as needed
    },
    langHe: {
      // General
      'ok': 'אישור',
      'close': 'סגור',
      'cancel': 'ביטול',
      'continue': 'המשך',
      'create': 'צור',
      'join': 'הצטרף',
      'player1': 'שחקן 1',
      'player2': 'שחקן 2',
      'yourName': 'השם שלך',
      'enterYourName': 'הכנס שם',
      'waitingForPlayer': 'ממתין לשחקן להצטרף...',
      'roomCreated': 'החדר נוצר!',
      'roomPin': 'הקוד שלך הוא: {pin}\n\nשתף אותו עם חבר כדי לשחק.',
      'joinRoom': 'הצטרף לחדר',
      'createRoom': 'צור חדר',
      'onlineGame': 'משחק ברשת',
      'localGame': 'משחק מקומי',
      'playVsComputer': 'שחק נגד מחשב',
      'instructions': 'הוראות',
      'startGame': 'התחל משחק',
      'gameOver': 'סיום משחק',
      'winner': '{winner} מנצח!',
      'itsATie': 'תיקו!',
      'computer': 'מחשב',
      'computerHand': 'היד של המחשב',
      'yourHand': 'היד שלך',
      'turn': 'תור',
      'score': 'ניקוד',
      'time': 'זמן: ',
      'replaceLetter': 'החלף אות',
      'selectLetterToReplace': 'בחר אות להחלפה',
      'costPoints': 'עלות: {cost} נקודות ({count}{ordinal} החלפה)',
      'yourScore': 'הניקוד שלך: {score}',
      'letterReplaced': 'האות הוחלפה! -{cost} נקודות',
      'needPointsToReplace': 'צריך לפחות {cost} נקודות כדי להחליף אות!',
      'chooseLetterForJoker': 'בחר אות לג׳וקר',
      'bonusCollected': 'בונוס נאסף!',
      'invalidWordsFound': 'נמצאו מילים לא תקינות',
      'invalidWordsDesc': 'המילים הבאות לא נמצאות במילון:',
      'acceptWordsOrSkip': 'לקבל את המילים בכל זאת או לדלג על התור?',
      'skipTurn': 'דלג על תור',
      'acceptWords': 'קבל מילים',
      'totalPoints': 'סך הנקודות:',
      'extraTurnGained': 'הרווחת תור נוסף!',
      'invalid': 'לא תקין',
      'accepted': 'התקבל',
      'wordsCreated': 'מילים שנוצרו:',
      'synchronizing': 'מסנכרן מצב משחק...',
      'playerLeft': 'שחקן עזב',
      'playerLeftDesc': 'השחקן השני עזב את המשחק.',
      'turnSkipped': 'התור דולג',
      'turnSkippedDesc': 'לא עשית כלום והתור שלך דולג.',
      'invalidMove': 'מהלך לא תקין',
      'roomNotFound': 'החדר לא נמצא!',
      'enterValidPin': 'אנא הכנס קוד בן 6 ספרות.',
      'instructionsTitle': 'הוראות משחק',
      'deck': 'קופה: ',
      'endTurn': 'סיום תור',
      'handOf': 'היד של {name}',
      // Add more as needed
    },
  };

  static String get(String key, {required bool isHebrew, Map<String, String>? params}) {
    final lang = isHebrew ? langHe : langEn;
    String value = _localized[lang]?[key] ?? key;
    if (params != null) {
      params.forEach((k, v) {
        value = value.replaceAll('{$k}', v);
      });
    }
    return value;
  }
} 